# fly.toml app configuration file generated for react-socketio-ts-server on 2023-10-10T17:56:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "react-socketio-ts-server"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
